//! The skills compiled into enx, generated from `skills/`; a test checks
//! that every directory there is listed.

pub(super) const BUILTIN: &[(&str, &str)] = &[
    ("backend", include_str!("../../skills/backend/SKILL.md")),
    (
        "backend-api",
        include_str!("../../skills/backend-api/SKILL.md"),
    ),
    (
        "backend-errors",
        include_str!("../../skills/backend-errors/SKILL.md"),
    ),
    (
        "backend-auth",
        include_str!("../../skills/backend-auth/SKILL.md"),
    ),
    (
        "backend-data",
        include_str!("../../skills/backend-data/SKILL.md"),
    ),
    (
        "backend-jobs",
        include_str!("../../skills/backend-jobs/SKILL.md"),
    ),
    (
        "backend-integrations",
        include_str!("../../skills/backend-integrations/SKILL.md"),
    ),
    (
        "backend-security",
        include_str!("../../skills/backend-security/SKILL.md"),
    ),
    (
        "backend-observability",
        include_str!("../../skills/backend-observability/SKILL.md"),
    ),
    (
        "backend-testing",
        include_str!("../../skills/backend-testing/SKILL.md"),
    ),
    (
        "backend-stack-next",
        include_str!("../../skills/backend-stack-next/SKILL.md"),
    ),
    (
        "backend-stack-node",
        include_str!("../../skills/backend-stack-node/SKILL.md"),
    ),
    (
        "backend-stack-python",
        include_str!("../../skills/backend-stack-python/SKILL.md"),
    ),
    (
        "backend-stack-go",
        include_str!("../../skills/backend-stack-go/SKILL.md"),
    ),
    (
        "backend-stack-rust",
        include_str!("../../skills/backend-stack-rust/SKILL.md"),
    ),
    (
        "backend-stack-laravel",
        include_str!("../../skills/backend-stack-laravel/SKILL.md"),
    ),
    (
        "backend-caching",
        include_str!("../../skills/backend-caching/SKILL.md"),
    ),
    (
        "backend-files",
        include_str!("../../skills/backend-files/SKILL.md"),
    ),
    (
        "backend-graphql",
        include_str!("../../skills/backend-graphql/SKILL.md"),
    ),
    (
        "backend-realtime",
        include_str!("../../skills/backend-realtime/SKILL.md"),
    ),
    (
        "backend-search",
        include_str!("../../skills/backend-search/SKILL.md"),
    ),
    (
        "backend-stack-dotnet",
        include_str!("../../skills/backend-stack-dotnet/SKILL.md"),
    ),
    (
        "backend-stack-java",
        include_str!("../../skills/backend-stack-java/SKILL.md"),
    ),
    (
        "backend-stack-rails",
        include_str!("../../skills/backend-stack-rails/SKILL.md"),
    ),
    ("ui", include_str!("../../skills/ui/SKILL.md")),
    ("ui-layout", include_str!("../../skills/ui-layout/SKILL.md")),
    ("ui-audit", include_str!("../../skills/ui-audit/SKILL.md")),
    ("ui-themes", include_str!("../../skills/ui-themes/SKILL.md")),
    (
        "ui-reference-launch",
        include_str!("../../skills/ui-reference-launch/SKILL.md"),
    ),
    (
        "ui-reference-saas",
        include_str!("../../skills/ui-reference-saas/SKILL.md"),
    ),
    (
        "ui-reference-studio",
        include_str!("../../skills/ui-reference-studio/SKILL.md"),
    ),
    (
        "ui-reference-marketplace",
        include_str!("../../skills/ui-reference-marketplace/SKILL.md"),
    ),
    (
        "ui-stack-next",
        include_str!("../../skills/ui-stack-next/SKILL.md"),
    ),
    (
        "ui-stack-plain",
        include_str!("../../skills/ui-stack-plain/SKILL.md"),
    ),
    (
        "ui-stack-react",
        include_str!("../../skills/ui-stack-react/SKILL.md"),
    ),
    (
        "ui-stack-shadcn",
        include_str!("../../skills/ui-stack-shadcn/SKILL.md"),
    ),
    (
        "ui-stack-svelte",
        include_str!("../../skills/ui-stack-svelte/SKILL.md"),
    ),
    (
        "ui-stack-tailwind",
        include_str!("../../skills/ui-stack-tailwind/SKILL.md"),
    ),
    (
        "ui-stack-vue",
        include_str!("../../skills/ui-stack-vue/SKILL.md"),
    ),
    (
        "ui-page-dashboard",
        include_str!("../../skills/ui-page-dashboard/SKILL.md"),
    ),
    (
        "ui-page-docs",
        include_str!("../../skills/ui-page-docs/SKILL.md"),
    ),
    (
        "ui-page-form",
        include_str!("../../skills/ui-page-form/SKILL.md"),
    ),
    (
        "ui-page-landing",
        include_str!("../../skills/ui-page-landing/SKILL.md"),
    ),
    (
        "ui-page-list-detail",
        include_str!("../../skills/ui-page-list-detail/SKILL.md"),
    ),
    (
        "ui-page-local-business",
        include_str!("../../skills/ui-page-local-business/SKILL.md"),
    ),
    (
        "ui-page-portfolio",
        include_str!("../../skills/ui-page-portfolio/SKILL.md"),
    ),
    (
        "ui-page-settings",
        include_str!("../../skills/ui-page-settings/SKILL.md"),
    ),
    (
        "ui-page-sign-in",
        include_str!("../../skills/ui-page-sign-in/SKILL.md"),
    ),
    (
        "ui-part-avatars",
        include_str!("../../skills/ui-part-avatars/SKILL.md"),
    ),
    (
        "ui-part-back-to-top",
        include_str!("../../skills/ui-part-back-to-top/SKILL.md"),
    ),
    (
        "ui-part-badges",
        include_str!("../../skills/ui-part-badges/SKILL.md"),
    ),
    (
        "ui-part-breadcrumbs",
        include_str!("../../skills/ui-part-breadcrumbs/SKILL.md"),
    ),
    (
        "ui-part-buttons",
        include_str!("../../skills/ui-part-buttons/SKILL.md"),
    ),
    (
        "ui-part-cards",
        include_str!("../../skills/ui-part-cards/SKILL.md"),
    ),
    (
        "ui-part-charts",
        include_str!("../../skills/ui-part-charts/SKILL.md"),
    ),
    (
        "ui-part-choices",
        include_str!("../../skills/ui-part-choices/SKILL.md"),
    ),
    (
        "ui-part-cta",
        include_str!("../../skills/ui-part-cta/SKILL.md"),
    ),
    (
        "ui-part-dialogs",
        include_str!("../../skills/ui-part-dialogs/SKILL.md"),
    ),
    (
        "ui-part-drawers",
        include_str!("../../skills/ui-part-drawers/SKILL.md"),
    ),
    (
        "ui-part-faq",
        include_str!("../../skills/ui-part-faq/SKILL.md"),
    ),
    (
        "ui-part-footer",
        include_str!("../../skills/ui-part-footer/SKILL.md"),
    ),
    (
        "ui-part-forms",
        include_str!("../../skills/ui-part-forms/SKILL.md"),
    ),
    (
        "ui-part-header",
        include_str!("../../skills/ui-part-header/SKILL.md"),
    ),
    (
        "ui-part-hero",
        include_str!("../../skills/ui-part-hero/SKILL.md"),
    ),
    (
        "ui-part-images",
        include_str!("../../skills/ui-part-images/SKILL.md"),
    ),
    (
        "ui-part-links",
        include_str!("../../skills/ui-part-links/SKILL.md"),
    ),
    (
        "ui-part-lists",
        include_str!("../../skills/ui-part-lists/SKILL.md"),
    ),
    (
        "ui-part-loading",
        include_str!("../../skills/ui-part-loading/SKILL.md"),
    ),
    (
        "ui-part-menus",
        include_str!("../../skills/ui-part-menus/SKILL.md"),
    ),
    (
        "ui-part-navigation",
        include_str!("../../skills/ui-part-navigation/SKILL.md"),
    ),
    (
        "ui-part-notifications",
        include_str!("../../skills/ui-part-notifications/SKILL.md"),
    ),
    (
        "ui-part-page-header",
        include_str!("../../skills/ui-part-page-header/SKILL.md"),
    ),
    (
        "ui-part-pagination",
        include_str!("../../skills/ui-part-pagination/SKILL.md"),
    ),
    (
        "ui-part-pricing",
        include_str!("../../skills/ui-part-pricing/SKILL.md"),
    ),
    (
        "ui-part-search",
        include_str!("../../skills/ui-part-search/SKILL.md"),
    ),
    (
        "ui-part-sections",
        include_str!("../../skills/ui-part-sections/SKILL.md"),
    ),
    (
        "ui-part-sidebar",
        include_str!("../../skills/ui-part-sidebar/SKILL.md"),
    ),
    (
        "ui-part-social-proof",
        include_str!("../../skills/ui-part-social-proof/SKILL.md"),
    ),
    (
        "ui-part-tables",
        include_str!("../../skills/ui-part-tables/SKILL.md"),
    ),
    (
        "ui-part-tabs",
        include_str!("../../skills/ui-part-tabs/SKILL.md"),
    ),
    (
        "ui-part-tooltips",
        include_str!("../../skills/ui-part-tooltips/SKILL.md"),
    ),
    (
        "ui-page-blog",
        include_str!("../../skills/ui-page-blog/SKILL.md"),
    ),
    (
        "ui-page-errors",
        include_str!("../../skills/ui-page-errors/SKILL.md"),
    ),
    (
        "ui-page-onboarding",
        include_str!("../../skills/ui-page-onboarding/SKILL.md"),
    ),
    (
        "ui-page-shop",
        include_str!("../../skills/ui-page-shop/SKILL.md"),
    ),
    (
        "ui-part-chat",
        include_str!("../../skills/ui-part-chat/SKILL.md"),
    ),
    (
        "ui-part-command-palette",
        include_str!("../../skills/ui-part-command-palette/SKILL.md"),
    ),
    (
        "ui-part-dates",
        include_str!("../../skills/ui-part-dates/SKILL.md"),
    ),
    (
        "ui-part-empty-states",
        include_str!("../../skills/ui-part-empty-states/SKILL.md"),
    ),
    (
        "ui-part-media",
        include_str!("../../skills/ui-part-media/SKILL.md"),
    ),
    (
        "ui-part-steps",
        include_str!("../../skills/ui-part-steps/SKILL.md"),
    ),
    (
        "ui-part-uploads",
        include_str!("../../skills/ui-part-uploads/SKILL.md"),
    ),
    (
        "ui-stack-angular",
        include_str!("../../skills/ui-stack-angular/SKILL.md"),
    ),
    (
        "ui-stack-astro",
        include_str!("../../skills/ui-stack-astro/SKILL.md"),
    ),
    ("motion", include_str!("../../skills/motion/SKILL.md")),
    (
        "motion-timing",
        include_str!("../../skills/motion-timing/SKILL.md"),
    ),
    (
        "motion-reveal",
        include_str!("../../skills/motion-reveal/SKILL.md"),
    ),
    (
        "motion-interface",
        include_str!("../../skills/motion-interface/SKILL.md"),
    ),
    (
        "motion-drawings",
        include_str!("../../skills/motion-drawings/SKILL.md"),
    ),
    (
        "motion-demo",
        include_str!("../../skills/motion-demo/SKILL.md"),
    ),
    (
        "motion-performance",
        include_str!("../../skills/motion-performance/SKILL.md"),
    ),
    (
        "motion-comfort",
        include_str!("../../skills/motion-comfort/SKILL.md"),
    ),
    (
        "motion-audit",
        include_str!("../../skills/motion-audit/SKILL.md"),
    ),
    (
        "motion-stacks",
        include_str!("../../skills/motion-stacks/SKILL.md"),
    ),
    ("frontend", include_str!("../../skills/frontend/SKILL.md")),
    (
        "frontend-accessibility",
        include_str!("../../skills/frontend-accessibility/SKILL.md"),
    ),
    (
        "frontend-architecture",
        include_str!("../../skills/frontend-architecture/SKILL.md"),
    ),
    (
        "frontend-data",
        include_str!("../../skills/frontend-data/SKILL.md"),
    ),
    (
        "frontend-errors",
        include_str!("../../skills/frontend-errors/SKILL.md"),
    ),
    (
        "frontend-forms",
        include_str!("../../skills/frontend-forms/SKILL.md"),
    ),
    (
        "frontend-performance",
        include_str!("../../skills/frontend-performance/SKILL.md"),
    ),
    (
        "frontend-security",
        include_str!("../../skills/frontend-security/SKILL.md"),
    ),
    (
        "frontend-seo",
        include_str!("../../skills/frontend-seo/SKILL.md"),
    ),
    (
        "frontend-state",
        include_str!("../../skills/frontend-state/SKILL.md"),
    ),
    (
        "frontend-testing",
        include_str!("../../skills/frontend-testing/SKILL.md"),
    ),
    ("database", include_str!("../../skills/database/SKILL.md")),
    (
        "database-indexes",
        include_str!("../../skills/database-indexes/SKILL.md"),
    ),
    (
        "database-migrations",
        include_str!("../../skills/database-migrations/SKILL.md"),
    ),
    (
        "database-mongodb",
        include_str!("../../skills/database-mongodb/SKILL.md"),
    ),
    (
        "database-mysql",
        include_str!("../../skills/database-mysql/SKILL.md"),
    ),
    (
        "database-operations",
        include_str!("../../skills/database-operations/SKILL.md"),
    ),
    (
        "database-postgres",
        include_str!("../../skills/database-postgres/SKILL.md"),
    ),
    (
        "database-queries",
        include_str!("../../skills/database-queries/SKILL.md"),
    ),
    (
        "database-schema",
        include_str!("../../skills/database-schema/SKILL.md"),
    ),
    (
        "database-sqlite",
        include_str!("../../skills/database-sqlite/SKILL.md"),
    ),
    (
        "database-transactions",
        include_str!("../../skills/database-transactions/SKILL.md"),
    ),
    ("devops", include_str!("../../skills/devops/SKILL.md")),
    ("devops-ci", include_str!("../../skills/devops-ci/SKILL.md")),
    (
        "devops-containers",
        include_str!("../../skills/devops-containers/SKILL.md"),
    ),
    (
        "devops-deploy",
        include_str!("../../skills/devops-deploy/SKILL.md"),
    ),
    (
        "devops-iac",
        include_str!("../../skills/devops-iac/SKILL.md"),
    ),
    (
        "devops-kubernetes",
        include_str!("../../skills/devops-kubernetes/SKILL.md"),
    ),
    (
        "devops-networking",
        include_str!("../../skills/devops-networking/SKILL.md"),
    ),
    (
        "devops-observability",
        include_str!("../../skills/devops-observability/SKILL.md"),
    ),
    (
        "devops-platforms",
        include_str!("../../skills/devops-platforms/SKILL.md"),
    ),
    (
        "devops-security",
        include_str!("../../skills/devops-security/SKILL.md"),
    ),
    ("mobile", include_str!("../../skills/mobile/SKILL.md")),
    (
        "mobile-android",
        include_str!("../../skills/mobile-android/SKILL.md"),
    ),
    (
        "mobile-data",
        include_str!("../../skills/mobile-data/SKILL.md"),
    ),
    (
        "mobile-flutter",
        include_str!("../../skills/mobile-flutter/SKILL.md"),
    ),
    (
        "mobile-ios",
        include_str!("../../skills/mobile-ios/SKILL.md"),
    ),
    (
        "mobile-performance",
        include_str!("../../skills/mobile-performance/SKILL.md"),
    ),
    (
        "mobile-react-native",
        include_str!("../../skills/mobile-react-native/SKILL.md"),
    ),
    (
        "mobile-release",
        include_str!("../../skills/mobile-release/SKILL.md"),
    ),
    (
        "mobile-testing",
        include_str!("../../skills/mobile-testing/SKILL.md"),
    ),
    ("mobile-ux", include_str!("../../skills/mobile-ux/SKILL.md")),
    ("systems", include_str!("../../skills/systems/SKILL.md")),
    (
        "systems-c-cpp",
        include_str!("../../skills/systems-c-cpp/SKILL.md"),
    ),
    (
        "systems-concurrency",
        include_str!("../../skills/systems-concurrency/SKILL.md"),
    ),
    (
        "systems-ffi",
        include_str!("../../skills/systems-ffi/SKILL.md"),
    ),
    (
        "systems-formats",
        include_str!("../../skills/systems-formats/SKILL.md"),
    ),
    (
        "systems-memory",
        include_str!("../../skills/systems-memory/SKILL.md"),
    ),
    (
        "systems-os",
        include_str!("../../skills/systems-os/SKILL.md"),
    ),
    (
        "systems-rust",
        include_str!("../../skills/systems-rust/SKILL.md"),
    ),
    ("testing", include_str!("../../skills/testing/SKILL.md")),
    (
        "testing-ci",
        include_str!("../../skills/testing-ci/SKILL.md"),
    ),
    (
        "testing-data",
        include_str!("../../skills/testing-data/SKILL.md"),
    ),
    (
        "testing-e2e",
        include_str!("../../skills/testing-e2e/SKILL.md"),
    ),
    (
        "testing-flaky",
        include_str!("../../skills/testing-flaky/SKILL.md"),
    ),
    (
        "testing-integration",
        include_str!("../../skills/testing-integration/SKILL.md"),
    ),
    (
        "testing-reproduce",
        include_str!("../../skills/testing-reproduce/SKILL.md"),
    ),
    (
        "testing-unit",
        include_str!("../../skills/testing-unit/SKILL.md"),
    ),
    ("docs", include_str!("../../skills/docs/SKILL.md")),
    ("docs-api", include_str!("../../skills/docs-api/SKILL.md")),
    (
        "docs-architecture",
        include_str!("../../skills/docs-architecture/SKILL.md"),
    ),
    (
        "docs-changelog",
        include_str!("../../skills/docs-changelog/SKILL.md"),
    ),
    (
        "docs-comments",
        include_str!("../../skills/docs-comments/SKILL.md"),
    ),
    (
        "docs-guides",
        include_str!("../../skills/docs-guides/SKILL.md"),
    ),
    (
        "docs-readme",
        include_str!("../../skills/docs-readme/SKILL.md"),
    ),
    (
        "docs-sites",
        include_str!("../../skills/docs-sites/SKILL.md"),
    ),
    ("security", include_str!("../../skills/security/SKILL.md")),
    (
        "security-auth",
        include_str!("../../skills/security-auth/SKILL.md"),
    ),
    (
        "security-crypto",
        include_str!("../../skills/security-crypto/SKILL.md"),
    ),
    (
        "security-infra",
        include_str!("../../skills/security-infra/SKILL.md"),
    ),
    (
        "security-privacy",
        include_str!("../../skills/security-privacy/SKILL.md"),
    ),
    (
        "security-secrets",
        include_str!("../../skills/security-secrets/SKILL.md"),
    ),
    (
        "security-supply-chain",
        include_str!("../../skills/security-supply-chain/SKILL.md"),
    ),
    (
        "security-web",
        include_str!("../../skills/security-web/SKILL.md"),
    ),
    (
        "performance",
        include_str!("../../skills/performance/SKILL.md"),
    ),
    (
        "performance-backend",
        include_str!("../../skills/performance-backend/SKILL.md"),
    ),
    (
        "performance-benchmarks",
        include_str!("../../skills/performance-benchmarks/SKILL.md"),
    ),
    (
        "performance-load",
        include_str!("../../skills/performance-load/SKILL.md"),
    ),
    (
        "performance-memory",
        include_str!("../../skills/performance-memory/SKILL.md"),
    ),
    (
        "performance-profiling",
        include_str!("../../skills/performance-profiling/SKILL.md"),
    ),
    ("review", include_str!("../../skills/review/SKILL.md")),
    (
        "review-checklists",
        include_str!("../../skills/review-checklists/SKILL.md"),
    ),
    ("research", include_str!("../../skills/research/SKILL.md")),
    (
        "research-code",
        include_str!("../../skills/research-code/SKILL.md"),
    ),
    (
        "research-libraries",
        include_str!("../../skills/research-libraries/SKILL.md"),
    ),
    (
        "research-web",
        include_str!("../../skills/research-web/SKILL.md"),
    ),
    ("librarian", include_str!("../../skills/librarian/SKILL.md")),
    (
        "orchestration",
        include_str!("../../skills/orchestration/SKILL.md"),
    ),
    ("code", include_str!("../../skills/code/SKILL.md")),
    ("writing", include_str!("../../skills/writing/SKILL.md")),
    ("i18n", include_str!("../../skills/i18n/SKILL.md")),
    (
        "brainstorming",
        include_str!("../../skills/brainstorming/SKILL.md"),
    ),
];
